// SPDX-License-Identifier: Apache-2.0
(()=>{'use strict';const $=id=>document.getElementById(id),token=()=>localStorage.getItem('jarvis_token')||localStorage.getItem('jarvis_chat_token')||'';const types=['TRIGGER','AGENT','LLM','TOOL','SKILL','MCP','KNOWLEDGE','CONDITION','PARALLEL','LOOP','APPROVAL','TRANSFORM','HTTP','DELAY','NOTIFICATION','RESULT'];let workflows=[],runs=[],agents=[],current='',nodes=[];
const api=async(path,options={})=>{const response=await fetch('/api'+path,{...options,headers:{Authorization:`Bearer ${token()}`,'Content-Type':'application/json'}}),data=await response.json();if(!response.ok)throw new Error(data.detail||'Anfrage fehlgeschlagen');return data};const status=value=>$('workflow-status').textContent=value||'';const el=(tag,text,cls)=>{const node=document.createElement(tag);node.textContent=text||'';if(cls)node.className=cls;return node};
function renderList(){const list=$('workflow-list');list.replaceChildren();if(!workflows.length)list.append(el('p','Noch keine Workflows.','empty'));workflows.forEach(flow=>{const button=el('button',flow.name,'workflow-item');button.onclick=()=>select(flow);list.append(button)})}
function nodeConfig(node,card){const config=node.config||{};if(['AGENT','LLM','TOOL','SKILL','MCP','KNOWLEDGE'].includes(node.type)){const select=document.createElement('select');select.ariaLabel='Agent';select.append(new Option('Agent waehlen',''));agents.forEach(agent=>select.append(new Option(agent.name,agent.id)));select.value=config.agent_id||'';select.onchange=()=>config.agent_id=select.value;card.append(select)}else if(node.type==='TRANSFORM'){const input=document.createElement('input');input.placeholder='Vorlage mit {value}';input.value=config.template||'{value}';input.oninput=()=>config.template=input.value;card.append(input)}else if(node.type==='DELAY'){const input=document.createElement('input');input.type='number';input.min=0;input.max=3600;input.value=config.seconds||0;input.oninput=()=>config.seconds=Number(input.value);card.append(input)}else if(node.type==='NOTIFICATION'){const input=document.createElement('input');input.placeholder='Titel';input.value=config.title||'Workflow';input.oninput=()=>config.title=input.value;card.append(input)}node.config=config}
function renderNodes(){const list=$('node-list');list.replaceChildren();nodes.forEach((node,index)=>{const card=el('article','','workflow-node'),head=document.createElement('header');head.append(el('strong',node.type),el('span',node.id));if(!['TRIGGER','RESULT'].includes(node.type)){const remove=el('button','×');remove.title='Node entfernen';remove.onclick=()=>{nodes.splice(index,1);renderNodes()};head.append(remove)}card.append(head);nodeConfig(node,card);list.append(card)});window.lucide?.createIcons()}
function select(flow){current=flow.id;$('workflow-name').value=flow.name;$('workflow-description').value=flow.description||'';nodes=structuredClone(flow.nodes);renderNodes()}
function reset(){current='';$('workflow-name').value='Neuer Workflow';$('workflow-description').value='';nodes=[{id:'trigger',type:'TRIGGER',config:{}},{id:'result',type:'RESULT',config:{}}];renderNodes()}
const body=()=>({name:$('workflow-name').value,description:$('workflow-description').value,enabled:true,nodes,edges:nodes.slice(0,-1).map((node,index)=>({source:node.id,target:nodes[index+1].id}))});
async function load(){try{[workflows,runs,agents]=await Promise.all([api('/workflows'),api('/workflows/runs'),api('/operations/agents')]);renderList();renderRuns();if(!current)reset();status('')}catch(error){status(error.message)}}
function renderRuns(){const list=$('workflow-runs');list.replaceChildren();runs.slice(0,12).forEach(run=>{const row=el('div','','run-item');row.append(el('strong',run.status),el('span',run.result||run.error||run.input));list.append(row)});if(!runs.length)list.append(el('p','Noch keine Laeufe.','empty'))}
$('node-type').replaceChildren(...types.filter(type=>!['TRIGGER','RESULT'].includes(type)).map(type=>new Option(type,type)));$('add-node').onclick=()=>{const type=$('node-type').value;nodes.splice(nodes.length-1,0,{id:`node_${crypto.randomUUID().slice(0,8)}`,type,config:{}});renderNodes()};$('new-workflow').onclick=reset;$('save-workflow').onclick=async()=>{try{const path=current?`/workflows/${current}`:'/workflows',saved=await api(path,{method:current?'PUT':'POST',body:JSON.stringify(body())});current=saved.id;await load();status('Gespeichert.')}catch(error){status(error.message)}};$('run-workflow').onclick=async()=>{if(!current)return status('Workflow zuerst speichern.');try{await api(`/workflows/${current}/runs`,{method:'POST',body:JSON.stringify({input:$('workflow-input').value})});status('Workflow gestartet.');setTimeout(()=>load().then(()=>status('Workflow gestartet.')),300)}catch(error){status(error.message)}};load();})();
